[tool.isort]
line_length = 100
import_heading_future = "Future library"
import_heading_stdlib = "Standard library"
import_heading_thirdparty = "Third-party"
import_heading_firstparty = "First-party"
import_heading_localfolder = "Relative"

[tool.black]
line-length = 100

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
ignore_missing_imports = true
check_untyped_defs = true


[tool.ruff]
line-length = 100
select = [
    # flake8-builtins
    "A",
    # flake8-annotations
    "ANN",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # pydocstyle
    "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pep8-naming
    "N",
    # flake8-pytest-style
    "PT",
    # flake8-return
    "RET",
    # flake8-bandit
    "S",
    # pyupgrade
    "UP",
    # pycodestyle
    "W"
]

ignore  = [
    # Missing type annotation for `self` in method
    "ANN101",
    # Missing type annotation for `cls` in method
    "ANN102",
    # Missing docstring in public <module|class|method|function>
    "D1"
]

[tool.ruff.per-file-ignores]
"test*.py" = [
    # Use of `assert` detected
    "S101"
]

[tool.coverage.run]
omit = [
    # omit interface codes
    "*/interfaces/*",
    # omit config classes
    "*/config*.py",
    ]
