name: Assign PR reviewers

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Get config file
        run: |
          curl -H "Authorization: token ${{ env.GITHUB_TOKEN }}" https://raw.githubusercontent.com/Travtus/.github/auto-assign-reviewers/.github/reviewer_config.yml > reviewer_config.yml
      - name: Request review based on files changes
        uses: necojackarc/auto-request-review@v0.12.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          config: reviewer_config.yml
          use_local: true
