name: Assign PR reviewers

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Request review based on files changes
        uses: necojackarc/auto-request-review@v0.12.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          config: .github/reviewer_config.yml
          use_local: true
