name: Build and deploy a docker image to ECR

on: 
  workflow_call:
    secrets:
      PAT_GITHUB:
        required: true
      AWS_OIDC_ROLE_ARN:
        required: true
      AWS_ACCOUNT:
        required: true
    inputs:
      AWS_REGION:
        required: false
        default: us-east-2
        type: string
      ECR_REPO_NAME:
        required: true
        type: string
      DOCKER_CONTEXT:
        required: false
        default: "."
        type: string
        description: "Docker build context path (defaults to repo root)"


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
  login-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: us-east-2
      - name: Login to ECR
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          AWS_REGION: ${{ inputs.AWS_REGION }}
        run: aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - name: Build Docker image
        env:
          ECR_REPO_NAME: ${{ inputs.ECR_REPO_NAME }}
          DOCKER_BUILD_CONTEXT: ${{ inputs.DOCKER_CONTEXT }}
        run: docker build --build-arg "GITHUB_TOKEN=${GITHUB_TOKEN}" -t "${ECR_REPO_NAME}" "${DOCKER_BUILD_CONTEXT}"
      - name: Tag Docker image
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          AWS_REGION: ${{ inputs.AWS_REGION }}
          ECR_REPO_NAME: ${{ inputs.ECR_REPO_NAME }}
        run: docker tag "${ECR_REPO_NAME}:latest" "${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:latest"
      - name: Push Docker image
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          AWS_REGION: ${{ inputs.AWS_REGION }}
          ECR_REPO_NAME: ${{ inputs.ECR_REPO_NAME }}
        run: docker push "${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:latest"
