name: Build and deploy a docker image to ECR

on: 
  workflow_call:
    secrets:
      PAT_GITHUB:
        required: true
      AWS_OIDC_ROLE_ARN:
        required: true
      AWS_ACCOUNT:
        required: true
    inputs:
      AWS_REGION:
        required: false
        default: us-east-2
        type: string
      ECR_REPO_NAME:
        required: true
        type: string


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
  login-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: us-east-2
      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ inputs.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com
      - name: Build Docker image
        run: docker build -t ${{ inputs.ECR_REPO_NAME }} . --build-arg GITHUB_TOKEN=$GITHUB_TOKEN
      - name: Tag Docker image
        run: docker tag ${{ inputs.ECR_REPO_NAME }}:latest ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR_REPO_NAME }}:latest
      - name: Push Docker image
        run: docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR_REPO_NAME }}:latest
