name: Create a release for a main branch

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      REPOSITORY:
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  get-new-tag:
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.get_new_tag.outputs.latest-tag}}
    steps:
      - uses: actions/checkout@v3
      - uses: octokit/request-action@v2.x
        id: get_latest_release_info
        with:
          route: GET /repos/Travtus/${{ inputs.REPOSITORY }}/releases/latest
      - id: get_new_tag
        run: python ./.github/workflows/get_new_tag.py ${{ toJson(steps.get_latest_release_info.outputs.data) }}
  tag-and-release:
    runs-on: ubuntu-latest
    needs: get-new-tag
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/Travtus/${{ inputs.REPOSITORY }}/releases
          tag_name: ${{ needs.get-new-tag.outputs.new-tag }}
          name: ${{ needs.get-new-tag.outputs.new-tag }}
          generate_release_notes: true
