name: Pull request checks

on:
  workflow_call:
    secrets:
      PAT_GITHUB:
        required: true
    inputs:
      PYTHON_VERSION:
        type: string
        default: "3.8"
        required: false
      ENABLE_PYTEST:
        type: boolean
        description: Run pytest against test files
        default: true
        required: false
      ENABLE_COVERAGE:
        type: boolean
        description: Run coverage.py against test files
        default: false
        required: false
      COVERAGE_THRESHOLD:
        type: number
        description: Test coverage for the repository
        default: 100
        required: false
      ENABLE_BDD:
        type: boolean
        description: Run BDD tests
        default: false
        required: false
      ENABLE_FORMAT:
        type: boolean
        description: Run format tools
        default: false
        required: false
      ENABLE_RUFF:
        type: boolean
        description: Run Ruff
        required: false
      ENABLE_MYPY:
        type: boolean
        description: Run mypy
        required: false
<<<<<<< Updated upstream
      RUN_CHECKOV_SCAN:
        type: boolean
        description: Run checkov IaC scans
        default: false
        required: false
      CHECKOV_SCAN_DIRECTORY:
        type: string
        description: Directory to run IaC scan against
        default: "."
        required: false
      CHECKOV_SCAN_FRAMEWORK:
        type: string
        description: Framework to use for checkov scans
        default: "cloudformation"
        required: false
      CHECKOV_OUTPUT_ONLY_FAILING_CHECKS:
        type: boolean
        description: Controls whether the checkov scan only displays failing checks
        default: true
=======
      ENABLE_DJANGO_TEST:
        type: boolean
        description: Run Django application tests
>>>>>>> Stashed changes
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
  PY_GLOB: "./**/*.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: Set up Python ${{ inputs.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
      - name: Get file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            changed_py:
              - added|modified: ${{ env.PY_GLOB }}
      - name: Install dependencies
        if: ${{ steps.filter.outputs.changed_py == 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pylint isort black mypy coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_testing.txt ]; then pip install -r requirements_testing.txt; fi
      - name: Format code
        if: ${{ steps.filter.outputs.changed_py == 'true' && inputs.ENABLE_FORMAT }}
        run: |
          isort ${{ steps.filter.outputs.changed_py_files }}
          black ${{ steps.filter.outputs.changed_py_files }}
      - name: Commit changes
        id: commit_changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format changed files
      - name: Check if commit
        if: ${{ steps.commit_changes.outputs.changes_detected == 'true' }}
        run: exit 1
      - name: Analysing the code with pylint
        if: ${{ steps.filter.outputs.changed_py == 'true' }}
        run: |
          # check for import errors
          pylint -d all -e E0401 **/*.py
      - name: Lint with flake8
        if: ${{ steps.filter.outputs.changed_py == 'true' }}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --max-line-length=127 --statistics
      - name: Lint with ruff
        if: ${{ steps.filter.outputs.changed_py == 'true' && inputs.ENABLE_RUFF }}
        uses: chartboost/ruff-action@v1
      - name: Type check with mypy
        if: ${{ steps.filter.outputs.changed_py == 'true' && inputs.ENABLE_MYPY }}
        run: |
          mypy ${{ steps.filter.outputs.changed_py_files }}
      - name: Test with pytest
        if: ${{ steps.filter.outputs.changed_py == 'true' && inputs.ENABLE_PYTEST }}
        run: |
          python -m pytest
      - name: Django test
        if: ${{ steps.filter.outputs.changed_py == 'true' && inputs.ENABLE_DJANGO_TEST }}
        run: |
          python manage.py test
      - name: Check test coverage
        if: ${{ steps.filter.outputs.changed_py == 'true' && inputs.ENABLE_COVERAGE }}
        run: |
          coverage run -m pytest
          coverage report -m --fail-under=${{ inputs.COVERAGE_THRESHOLD }}
      - name: Test with behave
        if: ${{ steps.filter.outputs.changed_py == 'true' && inputs.ENABLE_BDD }}
        run: |
          behave ./bdd_tests/features/
      - name: Run IaC SOC2 scans with checkov
        if: ${{ inputs.RUN_CHECKOV_SCAN }}
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.CHECKOV_SCAN_DIRECTORY }}
          framework: ${{ inputs.CHECKOV_SCAN_FRAMEWORK }}
          quiet: ${{ inputs.CHECKOV_OUTPUT_ONLY_FAILING_CHECKS }}
